version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9

    working_directory: ~/repo

    steps:
      - checkout

      # Download AWS CLI
      - run: sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
      - run: curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
      - run: sudo pip install -q awscli --upgrade

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build
      - run:
        name: Deploy to S3 if tests pass and branch is Master
        command: aws s3 sync public s3://www.murcul.com.s3-website-us-west-1.amazonaws.com --delete

