version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9

    working_directory: /tmp/repo

    steps:
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build
      - run: "aws s3 sync public s3://www.murcul.com.s3-website-us-west-1.amazonaws.com --delete"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
