version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9

    working_directory: /tmp/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      # store the build in the workspace to share it with deploy job
      - persist_to_workspace:
          root: /tmp
          paths:
            - repo/public/*
  deploy:
    docker:
      - image: "mesosphere/aws-cli"

    working_directory: /tmp
    steps:
      - attach_workspace:
          at: /tmp

      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync /tmp/repo/public s3://www.murcul.com.s3-website-us-west-1.amazonaws.com --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
